server:
  port: 0

spring:
  application:
    name: auth
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ssd018.synology.me:8806/auth?serverTimezone=UTC&characterEncoding=UTF-8
    username: auth
    password: Asdf123!@#
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
  main:
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://43.200.203.135:8761/eureka

encrypt:
  key-store:
    location: classpath:apiEncryptionKey.jks
    password: test1234
    alias: apiEncryptionKey

token:
  min_expiration_time: 3600000
  max_expiration_time: 864000000
  secret: '{cipher}AQDKFxedmeANfdFBnFAQOgFiK3MFZZTGnkPxHmoUOGbAIJ8JMqktFUffunj8We0HluP33QBVeEv9IuGnqPHzA8NBp/WbDsm9tov8PqG2YUtp5O69JRZHVDcLlRFE7C2IK4W873c4zo2wgnY5L8tfFz7HLY3STBzwMffns+Q44+B2nrHQt8B2CBj2r1bsW6SVP5QW9fzPDhWpxeBTgQRFI3WJLwrlXc/Z/BgkxBQIw/45UN0AyurqoXA/LupIJrLMCfMlrpJqOcZdbPHF9f+pY26QfnsjRJlLSSaWHudkJRZp4fi/9HRVhTThVTwSc3m4ojDXqoMpooHPnsOGyzSXniFmoaoWy72qFLW1BTIzHQ9f4jKLV+5owDklW4oFQAW40Wh0bK5A3GQ8yNUmjxvVGkc6'

gateway:
  ip: 43.200.203.135

member:
  url: http://MEMBER/member/members
  exception:
    No_SignUp: Bad Request Member Information.

logging:
  level:
    com.lotte.danuri.auth.client: DEBUG